name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - "build/basic/README.md"
      - "build/gitlab/README.md"
  workflow_dispatch:

jobs:
  build-basic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u liwei2633 -p ${{ secrets.DOCKER_HUB_PWD }}
      - name: Docker build
        run: |
          cd build/basic
          docker build -t liwei2633/yapi:1.9.2 .
          docker tag liwei2633/yapi:1.9.2 liwei2633/yapi:latest
          docker push liwei2633/yapi:1.9.2
          docker push liwei2633/yapi:latest
      - uses: peter-evans/dockerhub-description@v2
        with:
          username: liwei2633
          password: ${{ secrets.DOCKER_HUB_PWD }}
          repository: liwei2633/yapi
          readme-filepath: ./build/basic/README.md

  build-gitlab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u liwei2633 -p ${{ secrets.DOCKER_HUB_PWD }}
      - name: Docker build
        run: |
          cd build/gitlab
          docker build -t liwei2633/yapi-gitlab:1.9.2 .
          docker tag liwei2633/yapi-gitlab:1.9.2 liwei2633/yapi-gitlab:latest
          docker push liwei2633/yapi-gitlab:1.9.2
          docker push liwei2633/yapi-gitlab:latest
      - uses: peter-evans/dockerhub-description@v2
        with:
          username: liwei2633
          password: ${{ secrets.DOCKER_HUB_PWD }}
          repository: liwei2633/yapi-gitlab
          readme-filepath: ./build/gitlab/README.md
